# Generated by Django 5.2.6 on 2025-09-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("years_of_experience", models.IntegerField(default=1)),
                ("breed", models.CharField()),
                ("salary", models.FloatField(default=100.0)),
            ],
        ),
    ]
