# Generated by Django 5.2.6 on 2025-09-17 09:13

import cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cat",
            name="breed",
            field=models.CharField(
                max_length=100, validators=[cats.models.validate_cat_breed]
            ),
        ),
    ]
